spring:
  application:
    name: initialize-project
  profiles:
    active:
    - dev
    
goodsMgr:
   getAllGoodsesUrl: http://18.183.144.77:8080/goodses
   getGoodsByGoodsId: http://18.183.144.77:8080/goods/{0}
   deleteGoodsIdUrl: http://18.183.144.77:8080/goodses/{0}
   cheangInventoryUrl: http://18.183.144.77:8080/goods/{0}/inventory
   ordersUrl: http://18.183.144.77:8081/orders